dist: trusty

language: node_js
node_js:
  - '10.20'
  - '12.0'
  - '13.0'

addons:
  chrome: stable
  firefox: latest

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn

script:
  - yarn run test-headless

deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd projects/ng-imgix && npx semantic-release
  on:
    branch: next
